layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 15
  exclude:
    forks: false
    projects:
           hamidrezaamz.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # linkedin: your_username
  # medium: @your_username
  stackoverflow: 1508607
  telegram: HamidrezaAmz
  twitter: Hamidre34023732
  # youtube: your_username
  # vk: your_username

topics:
  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://raw.githubusercontent.com/github/explore/a3520d60fbf9b0bdd0b7d563a1a3ed596acd8489/topics/android/android.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/git/git.png

  - name: Google
    web_url: https://github.com/topics/google
    image_url: https://raw.githubusercontent.com/github/explore/204ebc99fea630a301fcb60f82358acd31cae857/topics/google/google.png

  - name: Gradle
    web_url: https://github.com/topics/gradle
    image_url: https://raw.githubusercontent.com/github/explore/e63ac6ef59c5c316574b0d31942f0534e51265a8/topics/gradle/gradle.png

  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/java/java.png

  - name: Kotlin
    web_url: https://github.com/topics/kotlin
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/kotlin/kotlin.png

  - name: Raspberry Pi
    web_url: https://github.com/topics/raspberry-pi
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/raspberry-pi/raspberry-pi.png

